### ISSUE TITLE
Image transition skips an image

### ISSUE THREAD

**Issue by crobibero** [3rob3/ImmichFrame#92] opened 2024-07-07 17:05 UTC
### Version

v1.0.5.0

### Deployment Method

Chromecast with Google TV

### Description

When the app loads the next image, it is skipped and a second image is shown after 1s instead of the configured duration (10s)

### Reproduction

1. Load album
2. Configure duration
3. See images skipped after 1s

### Expectations

Images should not be skipped

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment] 2024-07-07 17:30
Just to clarify, you don't have TransitionDuration set to 10 seconds do you?
Interval = time between images
TransitionDuration = fade in/fade out duration. Should be a small number like 1 or two seconds

**Comment by crobibero** [comment] 2024-07-07 18:00
Correct, the transition duration is 1s, and how long the image should be shown is 10s

**Comment by 3rob3** [comment] 2024-07-07 18:18
I am unable to reproduce, works correctly for me. If I reverse the two I get the behavior your describing.

**Comment by crobibero** [comment] 2024-07-07 18:56
After I restarted the device I was no longer able to reproduce the issue. I plan on looking into it when I get a chance

**Comment by 3rob3** [comment] 2024-07-10 01:39
Any update here? Can this be closed?

**Comment by crobibero** [comment] 2024-07-10 02:00
I haven't had a chance to see if I can reproduce the issue, likely won't for a week or two.

**Comment by 3rob3** [comment] 2024-07-11 21:46
i just saw this behavior. Did you enable screensaver? I think what happens is the screensaver seems to launch another instance of the app when it kicks in (even if it was already running) and they conflict with each other.

**Comment by crobibero** [comment] 2024-07-11 21:55
I left everything as default, I didn't see a place on the AndroidTV to disable the screensaver.

**Comment by 3rob3** [comment] 2024-07-11 21:57
you don't have to disable it, you have to enable it (so you probably didn't). It still seems to being running multiple instances concurrently. I will keep investigating.

**Comment by 3rob3** [comment] 2024-07-26 13:04
Pretty sure this was fixed in v1.0.6.0. If it is seen again I will create a new issue

**Closed by 3rob3** 2024-07-26 13:04 UTC
Labels: bug
